package at.aau.softwaredynamics.classifier.entities;

/**
 * ChangesTypes are take from ChangeDistiller and modified to fit CSharp changes
 */
public enum ChangeTypeLegacy {

    CLASS_INSERT,
    CLASS_DELETE,
    STATEMENT_DELETE,
    STATEMENT_INSERT,
    STATEMENT_ORDERING_CHANGE,
    STATEMENT_PARENT_CHANGE,
    STATEMENT_UPDATE,
    UNCLASSIFIED_CHANGE,
    CONDITION_EXPRESSION_CHANGE,
    CONDITION_EXPRESSION_INSERT,
    ALTERNATIVE_PART_INSERT,
    ALTERNATIVE_PART_DELETE,
    CLASS_RENAMING,
    PARENT_CLASS_CHANGE,
    PARENT_CLASS_DELETE,
    PARENT_CLASS_INSERT,
    PARENT_INTERFACE_CHANGE,
    PARENT_INTERFACE_DELETE,
    PARENT_INTERFACE_INSERT,
    METHOD_REMOVE,
    METHOD_INSERT,
    METHOD_RENAMING,
    METHOD_CHANGE,
    RETURN_TYPE_CHANGE,
    RETURN_TYPE_DELETE,
    RETURN_TYPE_INSERT,
    PARAMETER_DELETE,
    PARAMETER_INSERT,
    PARAMETER_ORDERING_CHANGE,
    PARAMETER_RENAMING,
    PARAMETER_TYPE_CHANGE,
    PARAMETER_CHANGE,
    //ATTRIBUTE_RENAMING,
    ATTRIBUTE_TYPE_CHANGE,
    FIELD_INSERT,
    FIELD_DELETE,
    FIELD_UPDATE,
    RETURN_STATEMENT_DELETE,
    RETURN_STATEMENT_INSERT,
    RETURN_STATEMENT_CHANGE,
    RETURN_STATEMENT_MOVE,
    METHOD_INVOCATION_INSERT,
    METHOD_INVOCATION_DELETE,
    METHOD_INVOCATION_CHANGE,
    METHOD_INVOCATION_MOVE,
    LAMBDA_EXPRESSION_INSERT,
    LAMBDA_EXPRESSION_DELETE,
    LAMBDA_EXPRESSION_CHANGE,
    CONSTRUCTOR_INVOCATION_DELETE,
    CONSTRUCTOR_INVOCATION_CHANGE,
    CONSTRUCTOR_INVOCATION_INSERT,
    LOOP_STATEMENT_INSERT,
    LOOP_STATEMENT_DELETE,
    LOOP_STATEMENT_UPDATE,
    ARGUMENT_CHANGE,
    ARGUMENT_INSERT,
    ARGUMENT_DELETE,
    ARGUMENT_MOVE,
    TYPE_ACCESS_INSERT,
    TYPE_ACCESS_DELETE,
    TYPE_ACCESS_UPDATE,
    CONSTRUCTOR_INSERT,
    CONSTRUCTOR_DELETE,
    CONSTRUCTOR_UPDATE,
    MODIFIER_INSERT,
    MODIFIER_DELETE,
    MODIFIER_UPDATE,
    INSERTED_HIERARCHICHAL_ELEMENT_UPDATE,
    IF_INSERT,
    IF_CHANGE,
    IF_DELETE
    ;

    /**
     * Returns number of change types.
     *
     * @return number of defined and extracted change types.
     */
    public static int getNumberOfChangeTypes() {
        return values().length;
    }
}