package differ.entities;

/**
 * ChangesTypes are take from ChangeDistiller and modified to fit CSharp changes
 */
public enum ChangeType {

    ADDITIONAL_CLASS,
    REMOVED_CLASS,
    IF_STATEMENT_DELETE,
    IF_STATEMENT_INSERT,
    IF_STATEMENT_ORDERING_CHANGE,
    IF_STATEMENT_PARENT_CHANGE,
    IF_STATEMENT_UPDATE,
    STATEMENT_DELETE,
    STATEMENT_INSERT,
    STATEMENT_ORDERING_CHANGE,
    STATEMENT_PARENT_CHANGE,
    STATEMENT_UPDATE,
    UNCLASSIFIED_CHANGE,
    CONDITION_EXPRESSION_CHANGE,
    ALTERNATIVE_PART_INSERT,
    ALTERNATIVE_PART_DELETE,
    CLASS_RENAMING,
    PARENT_CLASS_CHANGE,
    PARENT_CLASS_DELETE,
    PARENT_CLASS_INSERT,
    PARENT_INTERFACE_CHANGE,
    PARENT_INTERFACE_DELETE,
    PARENT_INTERFACE_INSERT,
    REMOVED_FUNCTIONALITY,
    ADDED_FUNCTIONALITY,
    RETURN_TYPE_CHANGE,
    RETURN_TYPE_DELETE,
    RETURN_TYPE_INSERT,
    METHOD_RENAMING,
    PARAMETER_DELETE,
    PARAMETER_INSERT,
    PARAMETER_ORDERING_CHANGE,
    PARAMETER_RENAMING,
    PARAMETER_TYPE_CHANGE,
    ATTRIBUTE_RENAMING,
    ATTRIBUTE_TYPE_CHANGE,
    ADDITIONAL_OBJECT_STATE,
    REMOVED_OBJECT_STATE,
    METHOD_INVOCATION_INSERT,
    METHOD_INVOCATION_DELETE,
    METHOD_INVOCATION_CHANGE,
    LAMBDA_EXPRESSION_INSERT,
    LAMBDA_EXPRESSION_DELETE,
    LAMBDA_EXPRESSION_CHANGE,
    CONSTRUCTOR_INVOCATION_DELETE,
    CONSTRUCTOR_INVOCATION_CHANGE,
    CONSTRUCTOR_INVOCATION_INSERT,
    LOOP_STATEMENT_INSERT,
    LOOP_STATEMENT_DELETE,
    LOOP_STATEMENT_UPDATE,
    IMPORT_STATEMENT_INSERT,
    IMPORT_STATEMENT_DELETE,
    IMPORT_STATEMENT_UPDATE,
    IMPORT_STATEMENT_ORDERING_CHANGE;


    /**
     * Returns number of change types.
     *
     * @return number of defined and extracted change types.
     */
    public static int getNumberOfChangeTypes() {
        return values().length;
    }
}